# Generated by Django 6.0.2 on 2026-02-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDE', '0002_conceptmastery'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='expected_output',
            field=models.TextField(blank=True, default='', help_text='The expected output of the program for validation.'),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True, default='', help_text='Reference solution code.'),
        ),
    ]
