# Generated by Django 6.0.2 on 2026-02-07 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDE', '0003_problem_expected_output_problem_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IDE.problem'),
        ),
    ]
