# Generated by Django 6.0.1 on 2026-02-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDE', '0004_interaction_problem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConceptMastery',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solution',
        ),
    ]
