# Generated by Django 6.0.2 on 2026-02-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
